// frontend/src/components/ExerciseList.vue
<!-- ExerciseList.vue -->
<template>
  <div class="container">
    <div class="exercise-card">
      <div class="card-header">
        <h5>運動項目列表</h5>
      </div>
      <div class="card-content">
        <button
          @click="fetchData"
          :disabled="isLoading"
          class="fetch-button"
        >
          <span v-if="isLoading" class="loading-spinner"></span>
          {{ isLoading ? '載入中...' : '獲取資料' }}
        </button>

        <div v-if="error" class="error-alert">
          <i class="bi bi-exclamation-triangle-fill error-icon"></i>
          {{ error }}
        </div>

        <div v-if="data" class="exercise-list">
          <div v-for="item in data"
               :key="item.id"
               class="exercise-item"
                @click="goToDetail(item.id)">
            <div class="item-header">
              <h5 class="item-title">{{ item.name }}</h5>
              <small class="item-id">ID: {{ item.id }}</small>
            </div>
            <p class="item-description">{{ item.description }}</p>
            <small class="item-time">
              創建時間: {{ formatDate(item.created_at) }}
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const data = ref(null)
const isLoading = ref(false)
const error = ref(null)
const router = useRouter()


const goToDetail = (id) => {
  router.push({
    name: 'exercise-detail',
    params: { id: id }
  })
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleString('zh-TW', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const fetchData = async () => {
  isLoading.value = true
  error.value = null

  try {
    const response = await fetch('http://127.0.0.1:11111/api/exercises/')
    if (!response.ok) {
      throw new Error('API 請求失敗')
    }
    data.value = await response.json()
  } catch (err) {
    error.value = err.message
  } finally {
    isLoading.value = false
  }
}
</script>


<style scoped>
.container {
  padding: 1.5rem;
}

.exercise-card {
  border: 1px solid #dee2e6;
  border-radius: 0.25rem;
  background-color: #fff;
}

.card-header {
  padding: 1rem;
  background-color: #f8f9fa;
  border-bottom: 1px solid #dee2e6;
}

.card-header h5 {
  margin: 0;
  font-size: 1.25rem;
}

.card-content {
  padding: 1rem;
}

.fetch-button {
  padding: 0.5rem 1rem;
  color: #fff;
  background-color: #0d6efd;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
  margin-bottom: 1rem;
}

.fetch-button:disabled {
  background-color: #6c757d;
  cursor: not-allowed;
}

.loading-spinner {
  display: inline-block;
  width: 1rem;
  height: 1rem;
  border: 0.2em solid currentColor;
  border-right-color: transparent;
  border-radius: 50%;
  animation: spinner-border 0.75s linear infinite;
  margin-right: 0.5rem;
}

.error-alert {
  padding: 1rem;
  margin-top: 1rem;
  color: #842029;
  background-color: #f8d7da;
  border: 1px solid #f5c2c7;
  border-radius: 0.25rem;
}

.error-icon {
  margin-right: 0.5rem;
}

.exercise-list {
  margin-top: 1rem;
}

.exercise-item {
    cursor: pointer;
  padding: 1rem;
  border: 1px solid #dee2e6;
  border-radius: 0.25rem;
  margin-bottom: 0.5rem;
}

.exercise-item:hover {
  background-color: #f0f0f0;
  transition: background-color 0.3s;
}

.item-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.item-title {
  margin: 0;
  font-size: 1.1rem;
}

.item-id {
  color: #6c757d;
}

.item-description {
  margin-bottom: 0.5rem;
}

.item-time {
  color: #6c757d;
}

@keyframes spinner-border {
  to { transform: rotate(360deg); }
}
</style>

// frontend/src/components/ExerciseList.jsx
import { useState, useEffect } from 'react'
import './ExerciseList.css'

function ExerciseList() {
    const [exercises, setExercises] = useState([])
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState(null)

    const fetchExercises = async () => {
        setLoading(true)
        setError(null)
        try {
            const response = await fetch('http://localhost:11111/api/exercises/')
            if (!response.ok) {
                throw new Error('網路請求失敗')
            }
            const data = await response.json()
            setExercises(data)
        } catch (err) {
            setError(err.message)
        } finally {
            setLoading(false)
        }
    }

    // 組件掛載時自動獲取數據
    useEffect(() => {
        fetchExercises()
    }, [])

    if (loading) {
        return (
            <div className="d-flex justify-content-center align-items-center min-vh-50">
                <div className="spinner-border loading-spinner text-primary" role="status">
                    <span className="visually-hidden">載入中...</span>
                </div>
            </div>
        )
    }

    return (
        <div className="container-fluid container-md py-3 py-md-4">
            <div className="exercise-header p-3 p-md-4 mb-3 mb-md-4">
                <div className="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3 gap-md-0">
                    <div className="w-100 w-md-auto">
                        <h1 className="h3 mb-2">運動項目列表</h1>
                        <p className="text-muted d-none d-md-block mb-0">探索並追蹤您的運動計劃</p>
                    </div>
                    <button
                        onClick={fetchExercises}
                        disabled={loading}
                        className="btn btn-primary w-100 w-md-auto d-flex align-items-center justify-content-center gap-2"
                    >
                        <i className="bi bi-arrow-clockwise"></i>
                        {loading ? '載入中...' : '重新載入'}
                    </button>
                </div>
            </div>

            {error && (
                <div className="alert alert-danger mx-2 mx-md-0" role="alert">
                    <i className="bi bi-exclamation-triangle-fill me-2"></i>
                    {error}
                </div>
            )}

            <div className="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3 g-md-4">
                {exercises.length === 0 ? (
                    <div className="col-12 text-center py-5">
                        <i className="bi bi-clipboard-x display-1 text-muted mb-4 d-block"></i>
                        <h3 className="h4 mb-3">尚無運動項目</h3>
                        <p className="text-muted">目前沒有任何運動項目。</p>
                    </div>
                ) : (
                    exercises.map((exercise) => (
                        <div className="col" key={exercise.id}>
                            <div className="card exercise-card h-100">
                                <div className="card-body">
                                    <div className="d-flex justify-content-between align-items-start mb-3">
                                        <h5 className="card-title text-truncate mb-0" title={exercise.name}>
                                            {exercise.name}
                                        </h5>
                                        <span className="badge bg-primary ms-2 text-nowrap">運動</span>
                                    </div>
                                    <p className="card-text exercise-description">
                                        {exercise.description}
                                    </p>
                                </div>
                                <div className="card-footer bg-light">
                                    <div className="d-flex flex-column gap-1">
                                        <small className="text-muted d-flex align-items-center">
                                            <i className="bi bi-calendar-plus me-2"></i>
                                            建立時間: {new Date(exercise.created_at).toLocaleString()}
                                        </small>
                                        <small className="text-muted d-flex align-items-center">
                                            <i className="bi bi-calendar-check me-2"></i>
                                            更新時間: {new Date(exercise.updated_at).toLocaleString()}
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    )
}

export default ExerciseList
